<#
.SYNOPSIS
    Publishes VibeCast as a self-contained single-file win-x64 build and copies
    the output to the shared release location.
#>

[CmdletBinding()]
param(
    [string]$Configuration = "Release",
    [string]$Destination = "\\Highlands\Applications\VibeCast"
)

$ErrorActionPreference = "Stop"

$root = $PSScriptRoot
$project = Join-Path $root "src\VibeCast\VibeCast.csproj"
$publishDir = Join-Path $root "src\VibeCast\bin\$Configuration\net10.0-windows\win-x64\publish"

Write-Host "Publishing VibeCast ($Configuration, win-x64, self-contained, single-file)..." -ForegroundColor Cyan

if (Test-Path $publishDir) {
    Remove-Item $publishDir -Recurse -Force
}

dotnet publish $project `
    -c $Configuration `
    -r win-x64 `
    --self-contained true `
    -p:PublishSingleFile=true `
    -p:IncludeNativeLibrariesForSelfExtract=true `
    -o $publishDir

if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed with exit code $LASTEXITCODE"
}

Write-Host "Publish succeeded. Output: $publishDir" -ForegroundColor Green

if (-not (Test-Path $Destination)) {
    Write-Host "Creating destination folder: $Destination" -ForegroundColor Cyan
    New-Item -ItemType Directory -Path $Destination -Force | Out-Null
}

Write-Host "Copying published files to $Destination ..." -ForegroundColor Cyan

# $Destination is the LIVE app folder (podcasts.db, backups\, downloads\, config.json,
# run.lock, logs\ all live there at runtime). Never mirror/delete the destination root -
# only overlay the fresh binaries. /E copies subfolders but never removes files that
# aren't in the source.
robocopy $publishDir $Destination /E /XD wwwroot /R:2 /W:5 /NFL /NDL /NJH
$robocopyExit = $LASTEXITCODE
if ($robocopyExit -ge 8) {
    throw "robocopy failed with exit code $robocopyExit"
}

# wwwroot is purely static web assets generated by the build, so it's safe to mirror -
# stale assets from older publishes get removed here (and only here).
$publishWwwroot = Join-Path $publishDir "wwwroot"
$destWwwroot = Join-Path $Destination "wwwroot"
robocopy $publishWwwroot $destWwwroot /MIR /R:2 /W:5 /NFL /NDL /NJH
$robocopyExit = $LASTEXITCODE
if ($robocopyExit -ge 8) {
    throw "robocopy failed with exit code $robocopyExit"
}

Write-Host "VibeCast published and copied to $Destination" -ForegroundColor Green

pause
